#
# PySNMP MIB module DABING-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file://..\DABING-MIB.mib
# Produced by pysmi-0.3.4 at Sun Feb 27 15:06:43 2022
# On host ? platform ? version ? by user ?
# Using Python version 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
#
OctetString, ObjectIdentifier, Integer = mibBuilder.importSymbols("ASN1", "OctetString", "ObjectIdentifier", "Integer")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsUnion, ConstraintsIntersection, ValueSizeConstraint, SingleValueConstraint, ValueRangeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsUnion", "ConstraintsIntersection", "ValueSizeConstraint", "SingleValueConstraint", "ValueRangeConstraint")
NotificationGroup, ModuleCompliance = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance")
Gauge32, ModuleIdentity, TimeTicks, MibScalar, MibTable, MibTableRow, MibTableColumn, iso, IpAddress, Counter64, Bits, Integer32, enterprises, Counter32, NotificationType, Unsigned32, ObjectIdentity, MibIdentifier = mibBuilder.importSymbols("SNMPv2-SMI", "Gauge32", "ModuleIdentity", "TimeTicks", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "iso", "IpAddress", "Counter64", "Bits", "Integer32", "enterprises", "Counter32", "NotificationType", "Unsigned32", "ObjectIdentity", "MibIdentifier")
TextualConvention, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "DisplayString")
dabing = ModuleIdentity((1, 3, 6, 1, 4, 1, 55532))
dabing.setRevisions(('2020-10-21 00:00',))
if mibBuilder.loadTexts: dabing.setLastUpdated('202010210000Z')
if mibBuilder.loadTexts: dabing.setOrganization('www.stuba.sk')
dabingParameters = MibIdentifier((1, 3, 6, 1, 4, 1, 55532, 1))
dabingAgentInfo = MibIdentifier((1, 3, 6, 1, 4, 1, 55532, 2))
dabingNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 55532, 3))
dabingNotificationPrefix = MibIdentifier((1, 3, 6, 1, 4, 1, 55532, 3, 1))
dabingNotificationObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 55532, 3, 2))
dabingChannel = MibScalar((1, 3, 6, 1, 4, 1, 55532, 1, 1), OctetString().clone('12C')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: dabingChannel.setStatus('current')
dabingInterval = MibScalar((1, 3, 6, 1, 4, 1, 55532, 1, 2), OctetString().clone('960')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: dabingInterval.setStatus('current')
dabingAgentIdentifier = MibScalar((1, 3, 6, 1, 4, 1, 55532, 2, 1), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: dabingAgentIdentifier.setStatus('current')
dabingAgentHostname = MibScalar((1, 3, 6, 1, 4, 1, 55532, 2, 2), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: dabingAgentHostname.setStatus('current')
dabingAgentLocation = MibScalar((1, 3, 6, 1, 4, 1, 55532, 2, 3), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: dabingAgentLocation.setStatus('current')
dabingAgentStatus = MibScalar((1, 3, 6, 1, 4, 1, 55532, 2, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: dabingAgentStatus.setStatus('current')
dabingGenericPayload = MibScalar((1, 3, 6, 1, 4, 1, 55532, 3, 2, 1), OctetString().clone('TEST')).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: dabingGenericPayload.setStatus('current')
dabingMalfunctioningBroadcastingTrap = NotificationType((1, 3, 6, 1, 4, 1, 55532, 3, 1, 1)).setObjects(("DABING-MIB", "dabingGenericPayload"))
if mibBuilder.loadTexts: dabingMalfunctioningBroadcastingTrap.setStatus('current')
dabingTestTrap = NotificationType((1, 3, 6, 1, 4, 1, 55532, 3, 1, 2)).setObjects(("DABING-MIB", "dabingGenericPayload"))
if mibBuilder.loadTexts: dabingTestTrap.setStatus('current')
mibBuilder.exportSymbols("DABING-MIB", PYSNMP_MODULE_ID=dabing, dabingAgentIdentifier=dabingAgentIdentifier, dabingAgentLocation=dabingAgentLocation, dabingChannel=dabingChannel, dabingNotificationObjects=dabingNotificationObjects, dabingMalfunctioningBroadcastingTrap=dabingMalfunctioningBroadcastingTrap, dabingAgentStatus=dabingAgentStatus, dabing=dabing, dabingNotificationPrefix=dabingNotificationPrefix, dabingNotifications=dabingNotifications, dabingAgentHostname=dabingAgentHostname, dabingAgentInfo=dabingAgentInfo, dabingInterval=dabingInterval, dabingGenericPayload=dabingGenericPayload, dabingParameters=dabingParameters, dabingTestTrap=dabingTestTrap)
